services:
  windows:
    image: dockurr/windows
    container_name: windows_10_temp
    environment:
      VERSION: "win10"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
      - 22:22/SSH
    stop_grace_period: 2m

